### ISSUE TITLE
ValueError: Trying to set a tensor of shape torch.Size([3072, 128]) in "weight" (which has shape torch.Size([3072, 16, 2, 2])), this looks incorrect.

### ISSUE THREAD

**Issue by nitinmukesh** [THUDM/CogVideo#510]
### System Info / 系統信息

torch 2.5.1+cu121
diffusers 0.31.0
transformers>=4.46.2
accelerate>=1.1.1
imageio-ffmpeg>=0.5.1
Python 3.11.10
Windows 11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
(C:\aitools\CogVideo\cv_venv) C:\aitools\CogVideo>python inference/cli_demo.py --prompt "A girl riding a bike." --model_path THUDM/CogVideoX1.5-5B --generate_type "t2v"
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████| 4/4 [00:17<00:00,  4.27s/it]
Loading pipeline components...:  20%|██████████████                                                        | 1/5 [00:17<01:08, 17.14s/it]The config attributes {'patch_bias': False, 'patch_size_t': 2} were passed to CogVideoXTransformer3DModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:  20%|██████████████                                                        | 1/5 [00:17<01:09, 17.32s/it]
Traceback (most recent call last):
  File "C:\aitools\CogVideo\inference\cli_demo.py", line 179, in <module>
    generate_video(
  File "C:\aitools\CogVideo\inference\cli_demo.py", line 84, in generate_video
    pipe = CogVideoXPipeline.from_pretrained(model_path, torch_dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 896, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 704, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\accelerate\big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\accelerate\utils\modeling.py", line 1780, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "C:\aitools\CogVideo\cv_venv\Lib\site-packages\accelerate\utils\modeling.py", line 286, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([3072, 128]) in "weight" (which has shape torch.Size([3072, 16, 2, 2])), this looks incorrect.
```

Also specified width/height and same error

`(C:\aitools\CogVideo\cv_venv) C:\aitools\CogVideo>python inference/cli_demo.py --prompt "A girl riding a bike." --model_path THUDM/CogVideoX1.5-5B --generate_type "t2v" --width 1360 --height 768`

### Expected behavior / 期待表现

It should start the inference.

**Comment by zRzRzRzRzRzRzR** [comment]
https://github.com/huggingface/diffusers/pull/9877

https://github.com/zRzRzRzRzRzRzR/diffusers/tree/cogvideox1.1-5b
Try installing diffusers from here, as the PR has not been merged yet.

**Comment by nitinmukesh** [comment]
Fixed.

**Comment by sunshinewhy** [comment]
> Fixed.

Can you tell me how do you fix the bug? I meet the same problem.

**Comment by chezolver** [comment]
I've tried the following:

```
.\python_embeded\Scripts\pip.exe install accelerate 
.\python_embeded\Scripts\pip.exe install git+https://github.com/zRzRzRzRzRzRzR/diffusers@cogvideox1.1-5b
```

And still getting the same error.

Running `.\python_embeded\Scripts\pip.exe list` gives me the following version for diffusers: `0.32.0.dev0` so it's definitely changed the version from `0.31.0`.

@zRzRzRzRzRzRzR @nitinmukesh what other steps did you do? I'm using the `ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\examples\cogvideox_1_5_5b_I2V_01.json` workflow.

**Comment by MaxHeuillet** [comment]
I am getting the same error using load_checkpoint_and_dispatch() method. How did you solve it?
